### ISSUE TITLE
AA 2.7 & ant build fails

### ISSUE THREAD

**Issue by pzmudzinski** [androidannotations/androidannotations#388]
```
[javac]     at org.apache.tools.ant.taskdefs.Sequential.execute(Sequential.java:68)
[javac]
[javac]     at com.android.ant.IfElseTask.execute(IfElseTask.java:120)
[javac]
[javac]     at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:291)
[javac]
[javac]     at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
[javac]
[javac]     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[javac]
[javac]     at java.lang.reflect.Method.invoke(Method.java:601)
[javac]
[javac]     at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
[javac]
[javac]     at org.apache.tools.ant.Task.perform(Task.java:348)
[javac]
[javac]     at org.apache.tools.ant.taskdefs.Sequential.execute(Sequential.java:68)
[javac]
[javac]     at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:291)
[javac]
[javac]     at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
[javac]
[javac]     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[javac]
[javac]     at java.lang.reflect.Method.invoke(Method.java:601)
[javac]
[javac]     at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
[javac]
[javac]     at org.apache.tools.ant.Task.perform(Task.java:348)
[javac]
[javac]     at org.apache.tools.ant.taskdefs.MacroInstance.execute(MacroInstance.java:398)
[javac]
[javac]     at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:291)
[javac]
[javac]     at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
[javac]
[javac]     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[javac]
[javac]     at java.lang.reflect.Method.invoke(Method.java:601)
[javac]
[javac]     at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
[javac]
[javac]     at org.apache.tools.ant.Task.perform(Task.java:348)
[javac]
[javac]     at org.apache.tools.ant.Target.execute(Target.java:392)
[javac]
[javac]     at org.apache.tools.ant.Target.performTasks(Target.java:413)
[javac]
[javac]     at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1399)
[javac]
[javac]     at org.apache.tools.ant.helper.SingleCheckExecutor.executeTargets(SingleCheckExecutor.java:38)
[javac]
[javac]     at org.apache.tools.ant.Project.executeTargets(Project.java:1251)
[javac]
[javac]     at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:442)
[javac]
[javac]     at org.apache.tools.ant.taskdefs.CallTarget.execute(CallTarget.java:105)
[javac]
[javac]     at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:291)
[javac]
[javac]     at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
[javac]
[javac]     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[javac]
[javac]     at java.lang.reflect.Method.invoke(Method.java:601)
[javac]
[javac]     at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
[javac]
[javac]     at org.apache.tools.ant.Task.perform(Task.java:348)
[javac]
[javac]     at org.apache.tools.ant.Target.execute(Target.java:392)
[javac]
[javac]     at org.apache.tools.ant.Target.performTasks(Target.java:413)
[javac]
[javac]     at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1399)
[javac]
[javac]     at org.apache.tools.ant.Project.executeTarget(Project.java:1368)
[javac]
[javac]     at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
[javac]
[javac]     at org.apache.tools.ant.Project.executeTargets(Project.java:1251)
[javac]
[javac]     at org.apache.tools.ant.Main.runBuild(Main.java:811)
[javac]
[javac]     at org.apache.tools.ant.Main.startAnt(Main.java:217)
[javac]
[javac]     at org.apache.tools.ant.launch.Launcher.run(Launcher.java:280)
[javac]
[javac]     at org.apache.tools.ant.launch.Launcher.main(Launcher.java:109)
[javac]
[javac]   Caused by: java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Integer
[javac]
[javac]     at com.googlecode.androidannotations.model.AndroidRes.idFromElement(AndroidRes.java:95)
[javac]
[javac]     ... 74 more
[javac]
[javac] C:\Users\me\workspace\<myapp>-Android\src\com\<myapp>\<myapp>Activity.java:64: error: Unexpected error. Please report an issue on AndroidAnnotations, with the following content: java.lang.RuntimeException: java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Integer
[javac]
[javac]     protected Intro intro;
[javac]                     ^
[javac]     at com.googlecode.androidannotations.model.AndroidRes.idFromElement(AndroidRes.java:97)
[javac]
[javac]     at com.googlecode.androidannotations.processing.ResProcessor.process(ResProcessor.java:60)
[javac]
[javac]     at com.googlecode.androidannotations.processing.ModelProcessor.process(ModelProcessor.java:47)
[javac]
[javac]     at com.googlecode.androidannotations.AndroidAnnotationProcessor.processAnnotations(AndroidAnnotationProcessor.java:472)
[javac]
[javac]     at com.googlecode.androidannotations.AndroidAnnotationProcessor.processThrowing(AndroidAnnotationProcessor.java:343)
[javac]
[javac]     at com.googlecode.androidannotations.AndroidAnnotationProcessor.process(AndroidAnnotationProcessor.java:318)
[javac]
[javac]     at com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:793)
[javac]
[javac]     at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:722)
[javac]
[javac]     at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$1700(JavacProcessingEnvironment.java:97)
[javac]
[javac]     at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1029)
[javac]
[javac]     at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1163)
[javac]
[javac]     at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1106)
[javac]
[javac]     at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:824)
[javac]
[javac]     at com.sun.tools.javac.main.Main.compile(Main.java:417)
[javac]
[javac]     at com.sun.tools.javac.main.Main.compile(Main.java:331)
[javac]
[javac]     at com.sun.tools.javac.main.Main.compile(Main.java:322)
[javac]
[javac]     at com.sun.tools.javac.Main.compile(Main.java:76)
[javac]
[javac]     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[javac]
[javac]     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
[javac]
[javac]     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[javac]
[javac]     at java.lang.reflect.Method.invoke(Method.java:601)
[javac]
[javac]     at org.apache.tools.ant.taskdefs.compilers.Javac13.execute(Javac13.java:56)
[javac]
[javac]     at org.apache.tools.ant.taskdefs.Javac.compile(Javac.java:1153)
[javac]
[javac]     at org.apache.tools.ant.taskdefs.Javac.execute(Javac.java:930)
[javac]
[javac]     at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:291)
[javac]
[javac]     at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
[javac]
[javac]     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[javac]
[javac]     at java.lang.reflect.Method.invoke(Method.java:601)
[javac]
[javac]     at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
[javac]
[javac]     at org.apache.tools.ant.Task.perform(Task.java:348)
[javac]
[javac]     at org.apache.tools.ant.taskdefs.Sequential.execute(Sequential.java:68)
[javac]
[javac]     at com.android.ant.IfElseTask.execute(IfElseTask.java:120)
[javac]
[javac]     at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:291)
[javac]
[javac]     at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
[javac]
[javac]     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[javac]
[javac]     at java.lang.reflect.Method.invoke(Method.java:601)
[javac]
[javac]     at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
[javac]
[javac]     at org.apache.tools.ant.Task.perform(Task.java:348)
[javac]
[javac]     at org.apache.tools.ant.taskdefs.Sequential.execute(Sequential.java:68)
[javac]
[javac]     at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:291)
[javac]
[javac]     at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
[javac]
[javac]     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[javac]
[javac]     at java.lang.reflect.Method.invoke(Method.java:601)
[javac]
[javac]     at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
[javac]
[javac]     at org.apache.tools.ant.Task.perform(Task.java:348)
[javac]
[javac]     at org.apache.tools.ant.taskdefs.MacroInstance.execute(MacroInstance.java:398)
[javac]
[javac]     at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:291)
[javac]
[javac]     at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
[javac]
[javac]     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[javac]
[javac]     at java.lang.reflect.Method.invoke(Method.java:601)
[javac]
[javac]     at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
[javac]
[javac]     at org.apache.tools.ant.Task.perform(Task.java:348)
[javac]
[javac]     at org.apache.tools.ant.Target.execute(Target.java:392)
[javac]
[javac]     at org.apache.tools.ant.Target.performTasks(Target.java:413)
[javac]
[javac]     at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1399)
[javac]
[javac]     at org.apache.tools.ant.helper.SingleCheckExecutor.executeTargets(SingleCheckExecutor.java:38)
[javac]
[javac]     at org.apache.tools.ant.Project.executeTargets(Project.java:1251)
[javac]
[javac]     at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:442)
[javac]
[javac]     at org.apache.tools.ant.taskdefs.CallTarget.execute(CallTarget.java:105)
[javac]
[javac]     at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:291)
[javac]
[javac]     at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
[javac]
[javac]     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[javac]
[javac]     at java.lang.reflect.Method.invoke(Method.java:601)
[javac]
[javac]     at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
[javac]
[javac]     at org.apache.tools.ant.Task.perform(Task.java:348)
[javac]
[javac]     at org.apache.tools.ant.Target.execute(Target.java:392)
[javac]
[javac]     at org.apache.tools.ant.Target.performTasks(Target.java:413)
[javac]
[javac]     at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1399)
[javac]
[javac]     at org.apache.tools.ant.Project.executeTarget(Project.java:1368)
[javac]
[javac]     at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
[javac]
[javac]     at org.apache.tools.ant.Project.executeTargets(Project.java:1251)
[javac]
[javac]     at org.apache.tools.ant.Main.runBuild(Main.java:811)
[javac]
[javac]     at org.apache.tools.ant.Main.startAnt(Main.java:217)
[javac]
[javac]     at org.apache.tools.ant.launch.Launcher.run(Launcher.java:280)
[javac]
[javac]     at org.apache.tools.ant.launch.Launcher.main(Launcher.java:109)
[javac]
[javac]   Caused by: java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Integer
[javac]
[javac]     at com.googlecode.androidannotations.model.AndroidRes.idFromElement(AndroidRes.java:95)
[javac]
[javac]     ... 74 more
[javac]
[javac] Note: Time measurements: [Whole Processing = 633 ms], [Validate Annotations = 127 ms], [Find R Classes = 47 ms], [Extract Manifest = 38 ms], [Extract Annotations = 36 ms],
[javac] C:\Users\me\workspace\<myapp>-Android\src\com\<myapp>\<myapp>Activity.java:28: error: cannot find symbol
[javac] import com.<myapp>.manual_tune.ManualTuneDialog_;
[javac]                                ^
[javac]   symbol:   class ManualTuneDialog_
[javac]   location: package com.<myapp>.manual_tune
[javac] C:\Users\me\workspace\<myapp>-Android\src\com\<myapp>\<myapp>Activity.java:74: error: cannot find symbol
[javac]     protected ClientCache_ clientCache;
[javac]               ^
[javac]   symbol:   class ClientCache_
[javac]   location: class <myapp>Activity
[javac] C:\Users\me\workspace\<myapp>-Android\src\com\<myapp>\config\Configuration.java:20: error: cannot find symbol
[javac]     ConfigurationCache_ cache;
[javac]     ^
[javac]   symbol:   class ConfigurationCache_
[javac]   location: class Configuration
[javac] C:\Users\me\workspace\<myapp>-Android\src\com\<myapp>\notifications\NotificationHandler.java:12: error: cannot find symbol
[javac] import com.<myapp>.<myapp>Activity_;
[javac]                    ^
[javac]   symbol:   class <myapp>Activity_
[javac]   location: package com.<myapp>
[javac] C:\Users\me\workspace\<myapp>-Android\src\com\<myapp>\chat\ChatFragment.java:21: error: cannot find symbol
[javac] import com.<myapp>.browser.BrowserActivity_;
[javac]                            ^
[javac]   symbol:   class BrowserActivity_
[javac]   location: package com.<myapp>.browser
[javac] C:\Users\me\workspace\<myapp>-Android\src\com\<myapp>\panel_popup\PanelDialogFragment.java:17: error: cannot find symbol
[javac] import com.<myapp>.chat.WebViewRowView_;
[javac]                         ^
[javac]   symbol:   class WebViewRowView_
[javac]   location: package com.<myapp>.chat
[javac] Note: Time measurements: [Whole Processing = 0 ms],
[javac] warning: Unclosed files for the types '[dummy1352302629516]'; these types will not undergo annotation processing
[javac] 8 errors
[javac] 1 warning
```

BUILD FAILED
C:\Users\me\workspace<myapp>-Android\build.xml:140: The following error occurred while executing this line:
C:\Users\me\workspace<myapp>-Android\custom_rules.xml:3: The following error occurred while executing this line:
C:\Users\me\workspace<myapp>-Android\custom_rules.xml:18: Compile failed; see the compiler error output for details.

Total time: 16 seconds

C:\Users\me\workspace<myapp>-Android>cd workspace/<myapp>-Android

It was working with AA 2.6 :-(
