### ISSUE TITLE
Error: cannot find symbol class MainActivity_ with gradle build 3.0.0

### ISSUE THREAD

**Issue by nttgithubntt** [androidannotations/androidannotations#2079]
**AndroidAnnotations version**:
4.4.0
**Android compile SDK version**:
   compileSdkVersion = 26
    buildToolsVersion = "26.0.2"
    supportLibVersion = "26.0.2"
  dependencies {
        classpath 'com.android.tools.build:gradle:3.0.0'
  }
annotationProcessor "org.androidannotations:androidannotations:4.4.0"
implementation "org.androidannotations:androidannotations-api:4.4.0"

```
 @EActivity(R.layout.seller_activity_main)
public class MainActivity extends DeepLinkEnabledActivity

```
manifest:
```
 <activity
            android:name="com.android.application.MainActivity_"
            android:launchMode="singleTop"
            android:screenOrientation="portrait"
            android:windowSoftInputMode="stateHidden|adjustResize" />
```

Error:(25, 30) error: cannot find symbol class MainActivity_

**Comment by zqr95518** [comment]
You can run once the error may disappear.

**Comment by Tumanin** [comment]
I have the same problem after update gradle from 2.3 to 3.0

**Comment by Tumanin** [comment]
Update: In my case the issue is not the gradle version, but the version of Android Studio. After update to Android Studio 3.0 even gradle 2.3.3 didn't generated classes on "Gradle Build". But in both cases if I press "Run" even with red colored generated classes, it starts running and then the error is gone. Amazing

**Comment by zqr95518** [comment]
Clean the project and try again? I don't have this error with Android Studio 3.0.

**Comment by Tumanin** [comment]
But "Run" the application works only if I set `compileSdkVersion 25`. If I try to set `compileSdkVersion 26` the library generates no classes at all. Tried "Clean", "Rebuild" and "Invalidate cache", nothing helps

**Comment by wijnanb** [comment]
I am experiencing the same issue. My configuration is the same as @Tumanin 
The classes will not generate after a clean build. It happens on `compileSdkVersion 25` and `compileSdkVersion 26`

**Comment by WonderCsabo** [comment]
Guys, can you create a sample reproducing project so we can investigate?

**Comment by Tumanin** [comment]
I resolved some third-party-issues and now I can run the project with `compileSdkVersion 26`. But Otto Integration doesn't work. I created a new [issue #2081 ](https://github.com/androidannotations/androidannotations/issues/2081)

**Comment by WonderCsabo** [comment]
Guys, please check out the wiki. In most of the cases, the problem is that you do not configure AA `resourcePackageName` option:

```groovy
android {
    // ...

    defaultConfig {
        // ...

        javaCompileOptions {
            annotationProcessorOptions {
                arguments = ["resourcePackageName": android.defaultConfig.applicationId]
            }
        }
    }
}
```

All other types of configuration related to manifest, or resource package name, should be removed.
Also, if you do not specify the `applicationId` in `defaultConfig` (you should), you can add the hardcoded string in the config above. Also, you should use the manifest package name here, so if the `applicationId` is different than that (should not be), then you also have to use hardcoded string in the config above.

Check out the [wiki](https://github.com/androidannotations/androidannotations/wiki/Building-Project-Gradle).

**Comment by wutq** [comment]
How to configure under Android Studio 3.0????   Very anxious ！！！

**Comment by nttgithubntt** [comment]
@wutq , you check comment of @WonderCsabo above. config as:

android {
    // ...

    defaultConfig {
        // ...

        javaCompileOptions {
            annotationProcessorOptions {
                arguments = ["resourcePackageName": android.defaultConfig.applicationId]
            }
        }
    }
}

**Comment by nttgithubntt** [comment]
thanks @WonderCsabo , you save my time.

**Comment by RunningShadow-007** [comment]
@nttgithubntt 
`
defaultConfig {
    javaCompileOptions {
        annotationProcessorOptions {
            arguments = ["resourcePackageName": android.defaultConfig.applicationId]
        }
    }
}
`

 this does not work for me

**Comment by Hoardon** [comment]
Still have the same issue. 

I apply and try all the solutions above with out success. 

Still doesn't work on Android Studio 3.0 and gradle version 2.3.x and 3.0

**Comment by latrevisani** [comment]
I was having the same issue. And searching for similar issues, I faced:
https://stackoverflow.com/questions/36685423/android-annotation-upgrade-to-4-0-0-build-error
So I replaced all my:
@Extra List<T>
by:
@Extra ArrayList<T>
And all those cannot find symbol _ errors were gone.

**Comment by swatisoni-ewebcore** [comment]
Guys, I'm facing the same issue after updating Android Studio & gradle 2.1.3 to 3.1.4.

I also tried all those answer but didn't resolve yet.
Plz help

**Comment by lsanotes** [comment]
@swatisoni-ewebcore paste your project configs here

**Comment by swatisoni-ewebcore** [comment]
@lsanotes I also tried with compileSdkVersion 26 but getting same error 

**gradle dependencies**
classpath 'com.android.tools.build:gradle:3.1.4'


**configs** 
compileSdkVersion 27
    buildToolsVersion '27.0.3'  
    flavorDimensions "default"

    defaultConfig {
        applicationId "com.merabreak"
        manifestPlaceholders = [onesignal_app_id               : "55044850-d77d-4b26-9d4b-d664efb9bfe1",
                                // Project number pulled from dashboard, local value is ignored.
                                onesignal_google_project_number: "REMOTE"]
        minSdkVersion 16
        targetSdkVersion 27
        versionCode 42
        versionName "3.1.6"
        multiDexEnabled true

        javaCompileOptions {
            annotationProcessorOptions {
                arguments = ["resourcePackageName": android.defaultConfig.applicationId]
                //includeCompileClasspath true
            }
        }
    }

**Comment by ciromine** [comment]
anyone could fix this? I have the same issue after update an old project to gradle 3, with Android Studio 3 :(.

**Comment by PauloCella** [comment]
I have a same problem on migrate Eclipse project to Android Studio Project. Annotations not generating 
this class  ex: ( MainActivity_ ) into generatedJava file

**Comment by dodgex** [comment]
can you guys please post your androidannotations.log located in `app\build\generated\source\apt` (or `app\build\generated\source\kapt` for kotlin)

**Comment by mohamedhamdy-Cis** [comment]
this my gradle file 

buildscript {
  repositories {
    google()
    jcenter()
  }
  dependencies {
    classpath "com.android.tools.build:gradle:3.2.1"
  }
}

repositories {
  mavenLocal()
  mavenCentral()
}

apply plugin: 'com.android.application'





repositories {
  flatDir {
    dirs 'libs'
  }
  google()
}



android {


  lintOptions {
    disable 'MissingTranslation'
    abortOnError false
  }
  compileSdkVersion 26

  android.buildToolsVersion "28.0.3"


  compileOptions {
    sourceCompatibility JavaVersion.VERSION_1_8
    targetCompatibility JavaVersion.VERSION_1_8
  }
  defaultConfig {
    applicationId "com.x.x"
    minSdkVersion 17
    versionCode 105
    targetSdkVersion 26
    //versionName "0.089"
    multiDexEnabled true
    renderscriptSupportModeEnabled true
    javaCompileOptions {
      annotationProcessorOptions {
        arguments = ["resourcePackageName": android.defaultConfig.applicationId,
                     "logAppenderConsole": "true"]

      }

    }

  }
  dexOptions {
    javaMaxHeapSize "4g"
  }
  buildTypes {
    debug {
      minifyEnabled false
      zipAlignEnabled true

      //proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
      // proguardFiles ('proguard-rules.pro')
    }
    release {
      minifyEnabled false
      zipAlignEnabled true
      //proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
//      proguardFiles('proguard-rules.pro')
    }
  }

  packagingOptions {
    exclude 'META-INF/DEPENDENCIES'
    exclude 'META-INF/DEPENDENCIES.txt'
    exclude 'META-INF/dependencies.txt'
    exclude 'META-INF/LICENSE.txt'
    exclude 'META-INF/notice.txt'
    exclude 'META-INF/LICENSE'
    exclude 'META-INF/NOTICE.txt'
    exclude 'META-INF/notice.txt'
    exclude 'META-INF/NOTICE'
  }

  sourceSets {
    main {
      manifest.srcFile 'src/main/AndroidManifest.xml'


    }
  }



}

dependencies {
  annotationProcessor "org.androidannotations:androidannotations:4.5.1"
  implementation 'org.androidannotations:androidannotations-api:4.5.1'
  implementation 'com.android.support:support-annotations:28.0.0'


  implementation fileTree(include: ['*.jar'], dir: 'libs')
  implementation(name: 'recycleview', ext: 'aar')
  implementation(name: 'robo', ext: 'aar')
  implementation(name: 'mupdf', ext: 'aar')
  implementation(name: 'views', ext: 'aar')
  implementation 'com.android.support:appcompat-v7:26.1.0'
  implementation 'com.android.support:support-v4:26.1.0'
  implementation 'com.android.support:design:26.1.0'
  implementation 'de.greenrobot:eventbus:2.2.1'
  implementation 'com.google.android.gms:play-services-analytics:16.0.4'
  implementation 'com.nostra13.universalimageloader:universal-image-loader:1.9.3'
  implementation 'com.fasterxml.jackson.core:jackson-core:2.4.3'
  implementation 'com.fasterxml.jackson.core:jackson-databind:2.4.3'
  implementation 'com.fasterxml.jackson.core:jackson-annotations:2.4.3'
  implementation 'com.github.chrisbanes.photoview:library:1.2.3'
  implementation 'com.facebook.stetho:stetho:1.1.1'
  implementation 'com.squareup.retrofit:retrofit:2.0.0-beta2'
  implementation 'com.squareup.okhttp:okhttp:2.7.5'
  implementation 'com.google.code.gson:gson:2.8.2'
  implementation 'com.squareup.retrofit2:retrofit:2.0.2'
  implementation 'com.squareup.retrofit2:converter-gson:2.0.2'
  implementation 'com.squareup.retrofit2:converter-jackson:2.0.0-beta4'
  implementation project(':simplealertdialog')
  //  implementation project(':MaterialSeachView')
  implementation 'com.miguelcatalan:materialsearchview:1.4.0'
  implementation project(':date4j')
  implementation project(':slidingmenu')
  implementation project(':stickyRecycleHeader')
  implementation project(':textReader')
  implementation 'com.github.bluejamesbond:textjustify-android:2.1.0'
  implementation 'org.jsoup:jsoup:1.11.1'
  implementation 'com.squareup.picasso:picasso:2.5.2'
  implementation 'com.github.clans:fab:1.6.3'
  implementation 'com.github.traex.rippleeffect:library:1.3'
  /* guava */
  implementation 'com.google.guava:guava:20.0'
  //Encoding library added for usin in mupdf
  implementation 'com.ibm.icu:icu4j:58.2'
  implementation 'com.j256.ormlite:ormlite-android:4.48'
  implementation 'com.j256.ormlite:ormlite-core:4.48'

  compile 'com.android.support:multidex:1.0.1'

}

 no androidannotations.log located in app\build\generated\source\apt

**Comment by dodgex** [comment]
@mohamedhamdy-Cis i see you have ` "logAppenderConsole": "true"` set, so you should have the logs in your build console. could you paste the logs ? just the build file does not help very much.

**Comment by dodgex** [comment]
The stacktrace has no indication to be directly related to android androidannotations.

are there other log messages? maybe coompiler errors? also could you try to run  `./gradlew clean build` ? the stacktrace looks like the issue happens while incrementally compiling stuff.

**Comment by WonderCsabo** [comment]
I am closing this issue. Please check the wiki and our example projects.

**Comment by ElyDantas** [comment]
Changing annotation processor for kapt solved my problem since i started using "apply plugin: 'kotlin-kapt'" in my gradle file.
