### ISSUE TITLE
Cannot find symbol errors after upgrading from 4.0 to 4.1

### ISSUE THREAD

**Issue by danielkummer** [androidannotations/androidannotations#1868]
I'm getting lots of "cannot find symbol" errors when upgrading the dependency from 4.0 to 4.1.

A clean doesn't solve the issue - also I'm not spotting any other error in the console logs.

Do you have any indication what could be responsible for the generation error in the newer 4.1 release?

**Comment by dodgex** [comment]
Your build / error log is the best error Indicator.

If you can post it we can check if you cant find it yourself

**Comment by WonderCsabo** [comment]
By default, the Java compiler limits the number of error messages to 100. It is possible that you have so much *cannot find symbol* errors, that the real error was cut out. You can show all errors this way in a `Gradle`-based build:

```groovy
gradle.projectsEvaluated {
    tasks.withType(JavaCompile) {
        options.compilerArgs << "-Xmaxerrs" << "99999"
    }
}
```

**Comment by WonderCsabo** [comment]
Closing issue due to lack of response.

**Comment by danielkummer** [comment]
Sorry - I was on vacation - thanks for the response, this is most probably the issue.

I'll verify on Monday :)

**Comment by aimanbaharum** [comment]
@WonderCsabo You're right, I just noticed this. Logcat limits the error lines by 100 by default. I didn't know there was a script that lets you un-limits it (I haven't tried the gradle script though).

But if it doesn't work either, try to remove all of the generated class imports, that will reduce the number of error lines in the logcat and you will eventually see where the real cause is from.

**Comment by jiuwu0905** [comment]
It's a great help to me. This problem makes me almost want to give up AA!!

**Comment by WonderCsabo** [comment]
@dodgex i thought about something: maybe we should only skip generation of a class if one of the decorating annotations of the holder annotation itself has an error. Currently we skip generation of all classes, even if there is only one error on one field annotation, but the codebase is correct across hundreds of other annotations.

**Comment by dodgex** [comment]
@WonderCsabo I already had a similar idea... we should try to generate as much as possible...

if possible maybe even classes where a validation error was but without the code for the invalid annotation instead adding a comment with the validation error in addition to the compiler error on the annotation usage.

---
did not mean to reopen this issue. hit that button on phone... we should open a new issue for that

**Comment by AllenCoder** [comment]
how to add 
```
gradle.projectsEvaluated {
    tasks.withType(JavaCompile) {
        options.compilerArgs << "-Xmaxerrs" << "99999"
    }
}
``

**Comment by aimanbaharum** [comment]
@AllenCoder put it in your project build.gradle file
