### ISSUE TITLE
Can't find symbol 'class_' after update to 4.5

### ISSUE THREAD

**Issue by jimisola** [androidannotations/androidannotations#2170]
**AndroidAnnotations version: 4.5
Android compile SDK version: 1.8
Android SDK Build-Tools: 28.0.3
com.android.tools.build:gradle: 3.2.1
Android Studio: 3.2.1
Gradle using gradlew: 4.6**

**Additional information:**
This error seems related to bug #2166. There are no class_ files generated.

My build worked with AA 4.4, com.android.tools.build:gradle: 3.1.4, AS 3.1.4 and Gradle 4.4.
I've tried to revert to that configuration but it doesn't work either. Spent some time troubleshooting and can't exclude an error on my side, but I'm basically stuck.

**Stacktrace:**
> Task :app:compileDebugJavaWithJavac FAILED
/home/jimisola/Dropbox/dev/jroster/app/src/main/java/com/jimisola/jroster/gui/fragments/SettingsFragment.java:22: error: cannot find symbol
import com.jimisola.jroster.gui.misc.AppPreferences_;

**project build.xml:**
buildscript {
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.2.1'
    }
}

allprojects {
    repositories {
        google()
        jcenter()
    }
}

**app build.xml:**
buildscript {
     repositories {
         google()
         jcenter()
    }
    dependencies {
    classpath 'com.android.tools.build:gradle:3.2.1'
    }
}

apply plugin: "com.android.application"

android {
    compileSdkVersion 26

    defaultConfig {
        applicationId "com.jimisola.jroster"
        versionCode 15
        versionName "0.42.1"

        minSdkVersion 26
        targetSdkVersion 26

        compileOptions {
            sourceCompatibility JavaVersion.VERSION_1_8
            targetCompatibility JavaVersion.VERSION_1_8
        }
    }

    sourceSets {
        main {
            java {
                srcDir "src"
                exclude "**/jroster/roster/cwp/**"
            }
        }
    }
    buildTypes {
        debug {
            debuggable true
            applicationIdSuffix ".debug"
        }

        release {
            minifyEnabled true // Enables code shrinking for the release build type
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
        }
    }
    lintOptions {
        // checkReleaseBuilds false
        // Or, if you prefer, you can continue to check for errors in release builds,
        // but continue the build even when errors are found:
        abortOnError false
    }

    def AAVersion = "4.5.0"

    dependencies {
        annotationProcessor "org.androidannotations:androidannotations:$AAVersion"
        annotationProcessor "org.androidannotations:ormlite:$AAVersion"
        implementation "org.androidannotations:androidannotations-api:$AAVersion"
        implementation "org.androidannotations:ormlite-api:$AAVersion"
        implementation 'net.sourceforge.htmlcleaner:htmlcleaner:2.13'
        implementation 'com.squareup.okio:okio:1.4.0'
        implementation 'com.squareup.okhttp:okhttp:2.4.0'
        implementation 'com.j256.ormlite:ormlite-android:4.48'
        implementation 'com.j256.ormlite:ormlite-core:4.48'
    }
}

clean {
    delete rootProject.buildDir
}

**Comment by vonclutch** [comment]
I had the same issue with 4.5.0 and the 4.6.0-SNAPSHOT.

Only the latest version 4.5.1 generate something for me.

**Comment by dodgex** [comment]
@jimisola can you confirm if this issue is still present with 4.5.1 for you?

**Comment by dodgex** [comment]
could you please clean the project (to ensure androidannotations.log is empty) and then run the build and post the androidannotations.log located in `app\build\generated\source\apt` (or `app\build\generated\source\kapt` for kotlin) here?

if it is to big or you are afraid it might disclose to many internal information send it to *support [[_A_T_]] androidannotations.org* with a small remark that its related to this issue.

I'll do my best to help you then. :)

**Comment by jimisola** [comment]
Mistake on my end. Apologies. Duplicate of #1888.

Added the following javaCompileOptions in defaultConfig:

javaCompileOptions {
  annotationProcessorOptions {
    arguments = ["resourcePackageName": android.defaultConfig.applicationId]
  }
}


Wish I'd known about /checked the androidannotations.log. Is there a reason why you don't write anything to screen during gradle? It would make it a lot more obvious even if was just a "Android Annotations ended prematurely check ..../../../androidannotations.log".

**Comment by dodgex** [comment]
Good that you found the issue. I'll close the issue then. :)


You can enable console logging by setting [`logAppenderConsole`](https://github.com/androidannotations/androidannotations/wiki/CustomizeAnnotationProcessing#logappenderconsole) to `true`.


for example:
```
javaCompileOptions {
	annotationProcessorOptions {
		arguments = ["resourcePackageName": android.defaultConfig.applicationId,
			"logAppenderConsole": "true"]
	}
} 
```


I have no idea why this is false by default... @WonderCsabo any idea

**Comment by naderz** [comment]
What im getting is the following error:

ERROR o.a.i.h.AndroidManifestFinder:147 - Could not find the AndroidManifest.xml file, using  generation folder

**Comment by dodgex** [comment]
@naderz  which verions of AA and android build plugin do you use?

**Comment by amasj2d** [comment]
I'm facing in the same situation ! I use Android Studio 3.3.0

**Comment by WonderCsabo** [comment]
For Android Gradle Plugin 3.3.0, you have to use AndroidAnnotations [4.6.0-SNAPSHOT](https://github.com/androidannotations/androidannotations/wiki/Building-Project-Gradle#setup). There is no stable version which supports AGP 3.3.0 yet, but we plan to release it soon.

**Comment by amasj2d** [comment]
@WonderCsabo Thanks a lot, you saved my day

**Comment by amasj2d** [comment]
@WonderCsabo Hi, Is the stable version done ?

**Comment by WonderCsabo** [comment]
[Yes.](https://github.com/androidannotations/androidannotations/wiki/ReleaseNotes#4.6.0)

**Comment by amasj2d** [comment]
Thanks you

**Comment by amasj2d** [comment]
Thanks you
